services:
  redroid-1:
    image: m3m012y/redroid-rockchip:12_opi5_v0.3
    stdin_open: true
    tty: true
    privileged: true
    ports:
      - 5551:5555
    volumes:
      - ~/data-1:/data
      - /dev/mali0:/dev/mali0
    command:
      - androidboot.redroid_gpu_mode=mali
      - androidboot.redroid_net_proxy_type=static
      - androidboot.redroid_width=720
      - androidboot.redroid_height=1280
      - androidboot.redroid_dpi=320
      - androidboot.redroid_fps=60
      - androidboot.redroid_radio=0
      - androidboot.redroid_wifi=1
      - androidboot.redroid_wifi_gateway=10.100.200.1/24
      # - ro.product.locale=th-TH
      - ro.product.model=Pixel 6
      - ro.product.brand=google
      - ro.product.device=oriole
      - ro.product.manufacturer=Google
      - ro.product.name=oriole
      - ro.product.build.fingerprint=google/oriole/oriole:12/SP1A.210812.016/7679548:user/release-keys

  redroid-2:
    image: m3m012y/redroid-rockchip:12_opi5_v0.4
    stdin_open: true
    tty: true
    privileged: true
    ports:
      - 5552:5555
    volumes:
      - ~/data-2:/data
      - /dev/mali0:/dev/mali0
    command:
      - androidboot.redroid_gpu_mode=mali
      - androidboot.redroid_net_proxy_type=static
      - androidboot.redroid_width=720
      - androidboot.redroid_height=1280
      - androidboot.redroid_dpi=320
      - androidboot.redroid_fps=60
      - androidboot.redroid_radio=0
      - androidboot.redroid_wifi=1
      - androidboot.redroid_wifi_gateway=10.100.200.1/24
      # - ro.product.locale=th-TH
      - ro.product.model=Pixel 6
      - ro.product.brand=google
      - ro.product.device=oriole
      - ro.product.manufacturer=Google
      - ro.product.name=oriole
      - ro.product.build.fingerprint=google/oriole/oriole:12/SP1A.210812.016/7679548:user/release-keys
